import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

interface ReportData {
  predictedClass: string;
  confidence: number;
  llmResponse: string;
  imageUrl: string;
}

export async function generateReport(data: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    // Collect the PDF chunks
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    // Header
    doc.fontSize(24)
       .font('Helvetica-Bold')
       .text('Skin Lesion Analysis Report', { align: 'center' });

    doc.moveDown();
    doc.fontSize(12)
       .font('Helvetica')
       .text(`Report Generated: ${new Date().toLocaleString()}`, { align: 'right' });

    doc.moveDown();
    doc.moveTo(50, doc.y)
       .lineTo(545, doc.y)
       .stroke();

    // Patient Information Section
    doc.moveDown();
    doc.fontSize(16)
       .font('Helvetica-Bold')
       .text('Analysis Results');

    doc.moveDown();
    doc.fontSize(12)
       .font('Helvetica')
       .text(`Predicted Condition: ${data.predictedClass.toUpperCase()}`)
       .text(`Confidence Level: ${data.confidence.toFixed(2)}%`);

    // Add image if available
    if (data.imageUrl) {
      doc.moveDown();
      try {
        doc.image(data.imageUrl, {
          fit: [250, 250],
          align: 'center'
        });
      } catch (error) {
        console.error('Error adding image to PDF:', error);
      }
    }

    // Recommendations Section
    doc.moveDown();
    doc.fontSize(16)
       .font('Helvetica-Bold')
       .text('Medical Recommendations');

    doc.moveDown();
    doc.fontSize(12)
       .font('Helvetica')
       .text(data.llmResponse, {
         align: 'justify',
         columns: 1
       });

    // Footer
    doc.moveDown();
    doc.moveTo(50, doc.y)
       .lineTo(545, doc.y)
       .stroke();

    doc.moveDown();
    doc.fontSize(10)
       .text('Disclaimer: This is an AI-generated report and should not be considered as a substitute for professional medical advice. Please consult with a qualified healthcare provider for proper diagnosis and treatment.', {
         align: 'justify',
         columns: 1
       });

    // Columbia University Logo and Attribution
    doc.moveDown();
    doc.fontSize(10)
       .text('Generated by Oncoscopic - Columbia University', { align: 'center' });

    // Finalize the PDF
    doc.end();
  });
} 